apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb-polyclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqldb-polyclinic
  template:
    metadata:
      labels:
        app: mysqldb-polyclinic
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: polyclinic
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: "Remindmetoforget.1304"
            - name: MYSQL_HOST
              value: "%"
          image: mysql/mysql-server
          imagePullPolicy: ""
          name: mysqldb-polyclinic
          ports:
            - containerPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: mysqldb-polyclinic
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    app: mysqldb-polyclinic
